export const FETCH_DATA_BY_CATEGORY_REQUEST = "FETCH_DATA_BY_CATEGORY_REQUEST";
export const FETCH_DATA_BY_CATEGORY_SUCCESS = "FETCH_DATA_BY_CATEGORY_SUCCESS";
export const FETCH_DATA_BY_CATEGORY_FAILURE = "FETCH_DATA_BY_CATEGORY_FAILURE";